language: rust
rust:
  - stable
  - beta
  - nightly
  - 1.36.0
matrix:
  allow_failures:
    - rust: nightly
  include:
  fast_finish: true
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache: cargo
