# not yet implemented, only for remote DB
# currently using local DB
#[database]
#url = "root@localhost/test"
#password = "12345"

[security]
# minimal length for passwords
password_min_length = 10
# Costs for bcrypt password verification
# Decreasing the value removes
bcrypt_cost = 10
# allows to disable TOTP two-factor authentication
disable_totp = true

[web] 
# 1 day 60*60*24
max_session_age_secs = 86400
# Bind IP, use 0.0.0.0 for anywhere if you know what you're doing
bind_ip = "127.0.0.1"
# Bind port
bind_port = 9000

[[services]]
# ID is required to bind user permissions and has to be unique
id = 0
# whether the service will be loaded
enabled = true
# service name
name = "TestIO"
# start service automatically
autostart = false
# allow command to be relative to work-dir of service-daemon
# otherwise it'll be treated as absolute
allow_relative = true
# command to run (application)
command = "target/debug/examples/test_io"
# absolute path required if not specified by allow_relative
directory = "target/debug/examples"
# arguments for command, set as [] to leave it empty
args = ["-jar","sample.jar"]
# stop-command, if set. Send to process stdin for stopping.
# Otherwise a process kill is required.
#soft_stop = "stop"
# restart on crash
restart = true
# restart also on no crash, normal termination (signal code 0)
restart_always = false
# Save last console output on service stop (non-user invoked), default false
snapshot_console_on_stop = true
# Save last console output on service crash, default true
snapshot_console_on_crash = true
# Save last console out on user invoked service stop, default false
snapshot_console_on_manual_stop = false
# Save last console out on user invoked service kill, default false
snapshot_console_on_manual_kill = false

[[services]]
id = 1
enabled = true
name = "ENV print"
autostart = false
allow_relative = true
command = "target/debug/examples/sec_env"
directory = "target/debug/examples"
args = []
restart = false

[[services]]
id = 2
enabled = true
name = "Ping"
autostart = true
allow_relative = true
command = "target/debug/examples/ping"
directory = "target/debug/examples"
args = []
restart = false

[[services]]
id = 3
enabled = true
name = "Mass IO"
autostart = true
allow_relative = true
command = "target/debug/examples/mass_io"
directory = "target/debug/examples"
args = []
restart = false