# not yet implemented, only for remote DB
# currently using local DB
#[database]
#url = "root@localhost/test"
#password = "12345"

[security]
# minimal length for passwords
password_min_length = 10
# Costs for bcrypt password verification
# Decreasing the value removes
bcrypt_cost = 10

[web]
# 1 day 60*60*24
max_session_age_secs = 86400

[[services]]
# ID is required to bind user permissions
id = 0
# whether the service will be loaded
enabled = false
# service name
name = "mc-server"
# start service automatically
autostart = false
# command to run (application)
command = "java"
# absolute paths, see issue #9
directory = "/foo/bar/"
# arguments for command
args = ["-jar","sample.jar"]
# stop-command, if set. Send to process stdin for stopping.
# Otherwise a process kill is required.
soft_stop = "stop"
# restart on crash
restart = true
# restart also on signal code 0 (no crash)
restart_always = true

[[services]]
id = 1
enabled = false
name = "cat utf8-lossy demo"
autostart = true
command = "/bin/cat"
directory = "/home"
args = ["~/.profile"]
restart = false